[package]
name = "midi-hkd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
easy-args = "0.3.0"
home = "0.5.5"
midir = "0.9.1"
toml = "0.7.3"
